# File   - Makefile
# Author - John H Allard
# Date   - 11/13/2014
# Info   - This is the makefile for the undirected graph data structure by John Allard. This makefile serves to build and run all of the unit tests
#			on the uGraph data structure and to build a simple executable contained in `Main/main.cpp'

CXXFLAGS=-g -std=c++11 -Wall 
SRCS = Vertex/Vertex.cpp UndirectedGraph/uGraph.cpp Edge/Edge.cpp AdjacencyList/AdjList.cpp Main/main.cpp
HDRS = Vertex/Vertex.h UndirectedGraph/uGraph.h Edge/Edge.h AdjacencyList/AdjList.h Main/main.h