# File   - Makefile
# Author - John H Allard
# Date   - 11/13/2014
# Info   - This is the makefile for the undirected graph data structure by John Allard. This makefile serves to build and run all of the unit tests
#			on the uGraph data structure and to build a simple executable contained in `Main/main.cpp'



all: 
	g++ -std=c++11 Main/main.cpp -o Main/main
	
